#server:
#  port: 8084
#  tomcat:
#    uri-encoding: UTF-8
#  servlet:
#    context-path: /reed

#静态图片获取
spring:
  mvc:
    static-path-pattern: /image/**
  resources:
    static-locations: file:/home/pic/
 #   static-locations: file:/Users/qufan/Downloads/pic/
  #设置上传文件的最大的大小
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  messages:
    encoding: UTF-8
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.101.47.253:3306/music_soft?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: reedfan1991


  mail:
    host: smtp.163.com
    username: m18915228146@163.com
    password: reed1991
    port: 25
    properties:
      mail:
        smtp:
          auth: true
          timeout: 25000




  redis:
    host: 47.101.47.253
    port: 6379
    password: root
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml    #  mybatis主配置文件所在路径
  mapper-locations: classpath:mybatis/mapper/*.xml  #  所有的mapper映射文件
  type-aliases-package: com.ustc.reed.pojo                       # 定义所有操作类的别名所在包


upload-path: /Users/qufan/Downloads/pic/


#   设置日志级别和日志路径
#logging:
#  file: /Users/qufan/Documents/log/sb01.log
#  level:
#    com:
#      ustc:
#        reed: DEBUG


