server:
  port: 8081
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: /reed


cupSize: F
spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  messages:
    encoding: UTF-8

#  spring.datasource.driver-class-name =com.mysql.jdbc.Driver
#  spring.datasource.url =jdbc:mysql://localhost:3306/springboot_mybatis
#  spring.datasource.username =root
#  spring.datasource.password =root